language: cpp
sudo: required
dist: trusty
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
      - MATRIX_EVAL="CXXCI=g++-5"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
    env:
      - MATRIX_EVAL="CXXCI=g++-6"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CXXCI=g++-7"
env:
  - OMP_NUM_THREADS=4
before_install:
  - eval "${MATRIX_EVAL}"
  - echo $CXXCI
script: make -j

